#tomcat 相关
server:
  port: ${SERVER_PORT:4396}
  tomcat:
    max-connections: 10000
    max-threads: 200
    min-spare-threads: 200
    connection-timeout: 5000ms

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: aixmi-sso-server
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    servlet:
      context-path: /aixmi-actuator
    port: 14396